// alo-frontend/src/pages/Meals.tsx
import React, { useState, useEffect } from 'react';
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Box,
  TextField,
} from '@mui/material';
import { mealsAPI, periodsAPI } from '../services/api';
import { getPersonColor } from '../styles/colors';
import { Period } from '../types';

const accountsConfig = {
  gourmich: ['Loïc', 'Mahaut', 'Alban', 'Ilan'],
  tigresse: ['Alice', 'Adèle', 'Joséphine', 'Albert', 'Oscar'],
};

type MealData = Record<string, Record<string, number>>;

export default function Meals() {
  const [mealData, setMealData] = useState<MealData>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activePeriod, setActivePeriod] = useState<Period | null>(null);

  const [selectedAccount, setSelectedAccount] = useState<'gourmich' | 'tigresse'>('gourmich');
  const [startDate, setStartDate] = useState<string>('');
  const [endDate, setEndDate] = useState<string>(new Date().toISOString().split('T')[0]);

  // Charger la période active au démarrage
  useEffect(() => {
    const loadPeriod = async () => {
      try {
        const response = await periodsAPI.getAll();
        const periods = response.data || [];
        const active = periods.find((p: Period) => p.status === 'draft');
        if (active) {
          setActivePeriod(active);
          setStartDate(active.start_date);
        }
      } catch (err) {
        console.error('Erreur chargement période:', err);
      }
    };
    loadPeriod();
  }, []);

  // Charger les repas sur la plage de dates
  useEffect(() => {
    if (!startDate || !endDate) return;

    const loadMeals = async () => {
      try {
        setLoading(true);
        const response = await mealsAPI.getRange(startDate, endDate, selectedAccount);
        setMealData(response.data);
        setError(null);
      } catch (err: any) {
        const errorMsg = err?.response?.data?.detail || err?.message || 'Erreur inconnue';
        setError(`Erreur : ${errorMsg}`);
        console.error('Erreur chargement repas:', { err, startDate, endDate, selectedAccount });
      } finally {
        setLoading(false);
      }
    };
    loadMeals();
  }, [startDate, endDate, selectedAccount]);

  const people = accountsConfig[selectedAccount];

  // Fonction pour obtenir le numéro de semaine ISO
  const getWeekNumber = (dateStr: string): number => {
    const d = new Date(dateStr);
    const dayNum = d.getDay() || 7;
    d.setDate(d.getDate() - dayNum + 4);
    const yearStart = new Date(d.getFullYear(), 0, 1);
    const weekNum = Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);
    return weekNum;
  };

  // Fonction pour calculer Pâques (algorithme de Meeus)
  const getEasterDate = (year: number): Date => {
    const a = year % 19;
    const b = Math.floor(year / 100);
    const c = year % 100;
    const d = Math.floor(b / 4);
    const e = b % 4;
    const f = Math.floor((b + 8) / 25);
    const g = Math.floor((b - f + 1) / 3);
    const h = (19 * a + b - d - g + 15) % 30;
    const i = Math.floor(c / 4);
    const k = c % 4;
    const l = (32 + 2 * e + 2 * i - h - k) % 7;
    const m = Math.floor((a + 11 * h + 22 * l) / 451);
    const month = Math.floor((h + l - 7 * m + 114) / 31);
    const day = ((h + l - 7 * m + 114) % 31) + 1;
    return new Date(year, month - 1, day);
  };

  // Jours fériés français
  const isPublicHoliday = (dateStr: string): boolean => {
    const d = new Date(dateStr);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const day = d.getDate();

    const dateCheck = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;

    // Jours fériés fixes
    const fixedHolidays = [
      `${year}-01-01`, // Jour de l'an
      `${year}-05-01`, // Fête du Travail
      `${year}-05-08`, // Victoire 1945
      `${year}-07-14`, // Fête nationale
      `${year}-08-15`, // Assomption
      `${year}-11-01`, // Toussaint
      `${year}-11-11`, // Armistice
      `${year}-12-25`, // Noël
    ];

    if (fixedHolidays.includes(dateCheck)) return true;

    // Jours fériés mobiles basés sur Pâques
    const easter = getEasterDate(year);

    // Lundi de Pâques (jour après Pâques)
    const easterMonday = new Date(easter);
    easterMonday.setDate(easterMonday.getDate() + 1);
    const mondayMonth = easterMonday.getMonth() + 1;
    const mondayDay = easterMonday.getDate();

    if (month === mondayMonth && day === mondayDay) return true;

    // Ascension (39 jours après Pâques)
    const ascension = new Date(easter);
    ascension.setDate(ascension.getDate() + 39);
    const ascensionMonth = ascension.getMonth() + 1;
    const ascensionDay = ascension.getDate();
    if (month === ascensionMonth && day === ascensionDay) return true;

    // Lundi de Pentecôte (50 jours après Pâques)
    const pentecost = new Date(easter);
    pentecost.setDate(pentecost.getDate() + 50);
    const pentecostMonth = pentecost.getMonth() + 1;
    const pentecostDay = pentecost.getDate();
    if (month === pentecostMonth && day === pentecostDay) return true;

    return false;
  };

  // Fonction pour vérifier si c'est un weekend (samedi=6, dimanche=0)
  const isWeekend = (dateStr: string): boolean => {
    const d = new Date(dateStr);
    const dayOfWeek = d.getDay();
    return dayOfWeek === 0 || dayOfWeek === 6;
  };

  const saveMeal = async (dateStr: string, person: string, value: number) => {
    try {
      const d = new Date(dateStr);
      const year = d.getFullYear();
      const month = d.getMonth() + 1;
      const day = d.getDate();

      await mealsAPI.saveMeal({
        year,
        month,
        day,
        account: selectedAccount,
        person,
        repas: value,
      });
    } catch (err: any) {
      console.error('Erreur sauvegarde repas:', err);
      setError(`Erreur sauvegarde: ${err?.response?.data?.detail || err?.message}`);
    }
  };

  const handleMealChange = (dateStr: string, person: string, value: string) => {
    const numValue = parseInt(value) || 0;
    setMealData(prev => ({
      ...prev,
      [dateStr]: {
        ...prev[dateStr],
        [person]: numValue,
      },
    }));
    saveMeal(dateStr, person, numValue);
  };

  // Calculer les totaux
  const totals = {
    byPerson: {} as Record<string, number>,
    total: 0,
  };

  Object.values(mealData).forEach(dayMeals => {
    people.forEach(person => {
      const count = dayMeals?.[person] || 0;
      totals.byPerson[person] = (totals.byPerson[person] || 0) + count;
    });
  });

  totals.total = Object.values(totals.byPerson).reduce((a, b) => a + b, 0);

  // Trier les dates en ordre décroissant (plus récent en haut)
  const sortedDates = Object.keys(mealData).sort((a, b) => new Date(b).getTime() - new Date(a).getTime());

  const periodLabel = activePeriod ? `${activePeriod.name} (${activePeriod.start_date} → ${activePeriod.end_date})` : 'Aucune période active';

  return (
    <div className="container">
      <h1>🍽️ Repas</h1>

      {error && (
        <div style={{ color: 'red', marginBottom: '20px', padding: '10px', backgroundColor: '#ffe0e0', borderRadius: '4px' }}>
          {error}
        </div>
      )}

      {/* Sélecteurs */}
      <Box sx={{ marginBottom: '20px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '15px' }}>
        <TextField
          label="Depuis"
          type="date"
          value={startDate}
          onChange={(e) => setStartDate(e.target.value)}
          slotProps={{ inputLabel: { shrink: true } }}
        />
        <TextField
          label="Jusqu'au"
          type="date"
          value={endDate}
          onChange={(e) => setEndDate(e.target.value)}
          slotProps={{ inputLabel: { shrink: true } }}
        />
        <FormControl>
          <InputLabel>Compte</InputLabel>
          <Select
            value={selectedAccount}
            label="Compte"
            onChange={(e) => setSelectedAccount(e.target.value as 'gourmich' | 'tigresse')}
          >
            <MenuItem value="gourmich">Gourmich</MenuItem>
            <MenuItem value="tigresse">Tigresse</MenuItem>
          </Select>
        </FormControl>
      </Box>

      {/* Info période */}
      <Box sx={{ marginBottom: '15px', padding: '10px', backgroundColor: '#e3f2fd', borderRadius: '4px', fontSize: '0.9em' }}>
        <strong>Période active :</strong> {periodLabel}
      </Box>

      {/* Résumé */}
      <Box sx={{ marginBottom: '20px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '15px' }}>
        {people.map(person => (
          <div key={person} style={{
            backgroundColor: getPersonColor(person as any),
            color: 'white',
            padding: '15px',
            borderRadius: '8px',
            textAlign: 'center',
          }}>
            <div style={{ fontSize: '0.9em', opacity: 0.9 }}>{person}</div>
            <div style={{ fontSize: '1.8em', fontWeight: 'bold', marginTop: '5px' }}>
              {totals.byPerson[person] || 0}
            </div>
            <div style={{ fontSize: '0.85em', opacity: 0.8, marginTop: '5px' }}>
              {totals.total > 0 ? `${((totals.byPerson[person] || 0) / totals.total * 100).toFixed(1)}%` : '0%'}
            </div>
          </div>
        ))}
        {/* Carte Total */}
        <div style={{
          backgroundColor: '#333333',
          color: 'white',
          padding: '15px',
          borderRadius: '8px',
          textAlign: 'center',
        }}>
          <div style={{ fontSize: '0.9em', opacity: 0.9 }}>Total</div>
          <div style={{ fontSize: '1.8em', fontWeight: 'bold', marginTop: '5px' }}>
            {totals.total}
          </div>
          <div style={{ fontSize: '0.85em', opacity: 0.8, marginTop: '5px' }}>
            repas
          </div>
        </div>
      </Box>

      {/* Tableau chronologique */}
      <TableContainer component={Paper} sx={{ marginBottom: '30px' }}>
        <Table size="small">
          <TableHead sx={{ backgroundColor: '#f5f5f5' }}>
            <TableRow>
              <TableCell sx={{ fontWeight: 'bold', minWidth: '120px' }}>Date</TableCell>
              {people.map(person => (
                <TableCell
                  key={person}
                  align="center"
                  sx={{
                    fontWeight: 'bold',
                    backgroundColor: getPersonColor(person as any),
                    color: 'white',
                    minWidth: '80px',
                  }}
                >
                  {person}
                </TableCell>
              ))}
              <TableCell align="center" sx={{ fontWeight: 'bold', backgroundColor: '#e0e0e0', minWidth: '70px' }}>
                Total
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={people.length + 2} align="center" sx={{ padding: '20px' }}>
                  Chargement…
                </TableCell>
              </TableRow>
            ) : sortedDates.length === 0 ? (
              <TableRow>
                <TableCell colSpan={people.length + 2} align="center" sx={{ padding: '20px', color: '#999' }}>
                  Aucun repas trouvé
                </TableCell>
              </TableRow>
            ) : (
              sortedDates.map(dateStr => {
                const dayMeals = mealData[dateStr];
                const dayTotal = people.reduce((sum, p) => sum + (dayMeals[p] || 0), 0);

                const weekNumber = getWeekNumber(dateStr);
                const isHoliday = isPublicHoliday(dateStr);
                const isWknd = isWeekend(dateStr);
                const isOddWeek = weekNumber % 2 === 1;

                let bgColor = '#ffffff';
                if (isHoliday || isWknd) {
                  bgColor = '#ffcccc';
                } else if (isOddWeek) {
                  bgColor = '#f0f4ff';
                }

                return (
                  <TableRow key={dateStr} sx={{ backgroundColor: bgColor, '&:hover': { backgroundColor: isHoliday || isWknd ? '#ffb3b3' : isOddWeek ? '#e8ecff' : '#f9f9f9' } }}>
                    <TableCell sx={{ fontWeight: '600', backgroundColor: 'inherit' }}>
                      {new Date(dateStr).toLocaleDateString('fr-FR', { weekday: 'short', month: 'short', day: 'numeric' })}
                    </TableCell>
                    {people.map(person => (
                      <TableCell key={`${dateStr}-${person}`} align="center" sx={{ backgroundColor: 'inherit' }}>
                        <TextField
                          type="number"
                          size="small"
                          slotProps={{ htmlInput: { min: 0, max: 4, style: { textAlign: 'center' } } }}
                          value={dayMeals[person] || 0}
                          onChange={(e) => handleMealChange(dateStr, person, e.target.value)}
                          sx={{
                            width: '60px',
                            '& input': { padding: '4px', fontSize: '0.9em' },
                          }}
                        />
                      </TableCell>
                    ))}
                    <TableCell align="center" sx={{ backgroundColor: 'inherit', fontWeight: '600' }}>
                      {dayTotal}
                    </TableCell>
                  </TableRow>
                );
              })
            )}
            {/* Ligne de totaux */}
            {sortedDates.length > 0 && (
              <TableRow sx={{ backgroundColor: '#f0f0f0', fontWeight: 'bold' }}>
                <TableCell sx={{ fontWeight: 'bold' }}>TOTAL</TableCell>
                {people.map(person => (
                  <TableCell key={`total-${person}`} align="center" sx={{ fontWeight: 'bold' }}>
                    {totals.byPerson[person] || 0}
                  </TableCell>
                ))}
                <TableCell align="center" sx={{ fontWeight: 'bold' }}>
                  {totals.total}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </TableContainer>
    </div>
  );
}

// frontend/src/routes/backoffice/meals/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';

	export let data: { backofficeToken?: string } = {};

	interface AccountConfig {
		[key: string]: string[];
	}

	interface MealData {
		[date: string]: {
			[person: string]: number;
		};
	}

	let mealData: MealData = {};
	let loading = true;
	let error: string | null = null;
	let accountsConfig: AccountConfig = {
		gourmich: [],
		tigresse: [],
	};
	let activePeriod: { name: string; start: string; end: string } | null = null;

	let selectedAccount: 'gourmich' | 'tigresse' = 'gourmich';
	let startDate = '';
	let endDate = new Date().toISOString().split('T')[0];
	let isExporting = false;

	const API_BASE = '/api';

	// Charger la configuration des comptes
	async function loadAccountsConfig() {
		try {
			const res = await fetch(`${API_BASE}/backoffice/meals/accounts`);
			if (res.ok) {
				accountsConfig = await res.json();
				// Initialiser startDate avec le premier jour du mois actuel
				const today = new Date();
				startDate = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-01`;
			}
		} catch (err) {
			console.error('Erreur chargement config:', err);
		}
	}

	// Formater la date pour affichage (ex: "24/05/2026")
	function formatDateFR(dateStr: string): string {
		const [year, month, day] = dateStr.split('-');
		return `${day}/${month}/${year}`;
	}

	// Mettre à jour la période active affichée
	function updateActivePeriod() {
		if (startDate && endDate) {
			activePeriod = {
				name: 'Période sélectionnée',
				start: formatDateFR(startDate),
				end: formatDateFR(endDate),
			};
		}
	}

	// Charger les repas
	async function loadMeals() {
		if (!startDate || !endDate) return;

		try {
			loading = true;
			error = null;
			updateActivePeriod();
			const params = new URLSearchParams({
				startDate,
				endDate,
				account: selectedAccount,
			});

			const headers = data.backofficeToken ? { Authorization: `Bearer ${data.backofficeToken}` } : {};
			const res = await fetch(`${API_BASE}/backoffice/meals/range?${params}`, { headers });

			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}

			mealData = await res.json();
		} catch (err: any) {
			error = `Erreur chargement: ${err.message}`;
			console.error('Error loading meals:', err);
		} finally {
			loading = false;
		}
	}

	// Enregistrer un repas
	async function saveMeal(dateStr: string, person: string, value: number) {
		try {
			const res = await fetch(`${API_BASE}/backoffice/meals/record`, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					...(data.backofficeToken && { Authorization: `Bearer ${data.backofficeToken}` }),
				},
				body: JSON.stringify({
					date: dateStr,
					person,
					meal: value,
					account: selectedAccount,
				}),
			});

			if (!res.ok) {
				const detail = await res.json();
				throw new Error(detail.error || `HTTP ${res.status}`);
			}
		} catch (err: any) {
			error = `Erreur sauvegarde: ${err.message}`;
			console.error('Error saving meal:', err);
		}
	}

	// Exporter les repas
	async function exportMeals() {
		try {
			isExporting = true;
			const res = await fetch(`${API_BASE}/backoffice/meals/export`, {
				headers: data.backofficeToken ? { Authorization: `Bearer ${data.backofficeToken}` } : {},
			});

			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}

			// Créer un blob et télécharger
			const blob = await res.blob();
			const url = window.URL.createObjectURL(blob);
			const link = document.createElement('a');
			link.href = url;
			link.download = `meals-${new Date().toISOString().split('T')[0]}.jsonl`;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);
			window.URL.revokeObjectURL(url);
		} catch (err: any) {
			error = `Erreur export: ${err.message}`;
			console.error('Error exporting meals:', err);
		} finally {
			isExporting = false;
		}
	}

	// Gestion changement repas
	function handleMealChange(dateStr: string, person: string, value: string) {
		const numValue = Math.max(0, Math.min(4, parseInt(value) || 0));
		if (!mealData[dateStr]) {
			mealData[dateStr] = {};
		}
		mealData[dateStr][person] = numValue;
		saveMeal(dateStr, person, numValue);
	}

	// Calculer totaux
	function calculateTotals() {
		const people = accountsConfig[selectedAccount] || [];
		const totals: { [person: string]: number } = {};
		let total = 0;

		Object.values(mealData).forEach((dayMeals) => {
			people.forEach((person) => {
				const count = dayMeals[person] || 0;
				totals[person] = (totals[person] || 0) + count;
				total += count;
			});
		});

		return { byPerson: totals, total };
	}

	// Trier les dates
	function getSortedDates() {
		return Object.keys(mealData).sort((a, b) => new Date(b).getTime() - new Date(a).getTime());
	}

	onMount(() => {
		// Auth check is done by +layout.server.ts (redirects to login if no token)
		loadAccountsConfig();
	});

	$: if (startDate && endDate) {
		loadMeals();
	}

	const totals = calculateTotals();
	const people = accountsConfig[selectedAccount] || [];
	const sortedDates = getSortedDates();

	// Couleurs personnalisées par personne
	const personColors: { [key: string]: string } = {
		'Loïc': '#2196F3',
		'Alice': '#FF5722',
		'Mahaut': '#4CAF50',
		'Alban': '#FFC107',
		'Ilan': '#9C27B0',
		'Adèle': '#00BCD4',
		'Oscar': '#8BC34A',
		'Albert': '#F44336',
		'Joséphine': '#E91E63',
	};

	const getPersonColor = (person: string) => personColors[person] || '#9E9E9E';
</script>

<div class="container">
	<h1>🍽️ Repas</h1>

	{#if error}
		<div class="error">{error}</div>
	{/if}

	{#if activePeriod}
		<div class="active-period">
			<strong>Période active :</strong>
			{activePeriod.name} ({activePeriod.start} → {activePeriod.end})
		</div>
	{/if}

	<!-- Sélecteurs -->
	<div class="controls">
			<div>
				<label>
					Depuis
					<input
						type="date"
						bind:value={startDate}
					/>
				</label>
			</div>

			<div>
				<label>
					Jusqu'au
					<input
						type="date"
						bind:value={endDate}
					/>
				</label>
			</div>

			<div>
				<label>
					Compte
					<select bind:value={selectedAccount}>
						<option value="gourmich">Gourmich</option>
						<option value="tigresse">Tigresse</option>
					</select>
				</label>
			</div>

			<button
				on:click={exportMeals}
				disabled={isExporting}
				class="btn-export"
			>
				{isExporting ? '⏳ Export...' : '⬇️ Exporter'}
			</button>
		</div>

		<!-- Résumé -->
		<div class="summary">
			{#each people as person (person)}
				<div
					class="summary-card"
					style="background-color: {getPersonColor(person)}"
				>
					<div class="person-name">{person}</div>
					<div class="person-total">{totals.byPerson[person] || 0}</div>
					<div class="person-percent">
						{totals.total > 0
							? ((totals.byPerson[person] || 0) / totals.total * 100).toFixed(1)
							: '0'}%
					</div>
				</div>
			{/each}

			<div class="summary-card total-card">
				<div class="person-name">Total</div>
				<div class="person-total">{totals.total}</div>
				<div class="person-percent">repas</div>
			</div>
		</div>

		<!-- Tableau -->
		{#if loading}
			<div class="loading">Chargement…</div>
		{:else if sortedDates.length === 0}
			<div class="no-data">Aucun repas trouvé</div>
		{:else}
			<table class="meals-table">
				<thead>
					<tr>
						<th>Date</th>
						{#each people as person (person)}
							<th
								style="background-color: {getPersonColor(person)}; color: white;"
							>
								{person}
							</th>
						{/each}
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					{#each sortedDates as dateStr (dateStr)}
						{@const dayMeals = mealData[dateStr] || {}}
						{@const dayTotal = people.reduce((sum, p) => sum + (dayMeals[p] || 0), 0)}
						<tr>
							<td class="date-cell">
								{new Date(dateStr).toLocaleDateString('fr-FR', {
									weekday: 'short',
									month: 'short',
									day: 'numeric',
								})}
							</td>
							{#each people as person (person)}
								<td>
									<input
										type="number"
										min="0"
										max="4"
										value={dayMeals[person] || 0}
										on:change={(e) =>
											handleMealChange(dateStr, person, e.currentTarget.value)}
										class="meal-input"
									/>
								</td>
							{/each}
							<td class="total-cell">{dayTotal}</td>
						</tr>
					{/each}

					<!-- Ligne totaux -->
					<tr class="totals-row">
						<td class="date-cell"><strong>TOTAL</strong></td>
						{#each people as person (person)}
							<td><strong>{totals.byPerson[person] || 0}</strong></td>
						{/each}
						<td class="total-cell"><strong>{totals.total}</strong></td>
					</tr>
				</tbody>
			</table>
		{/if}
</div>

<style>
	.container {
		max-width: 1200px;
		margin: 0 auto;
		padding: 20px;
		font-family: system-ui, -apple-system, sans-serif;
	}

	h1 {
		margin-top: 0;
		color: #333;
	}

	.error {
		background-color: #ffebee;
		color: #c62828;
		padding: 12px;
		border-radius: 4px;
		margin-bottom: 20px;
	}

	.active-period {
		background-color: #e3f2fd;
		color: #1976d2;
		padding: 12px;
		border-radius: 4px;
		margin-bottom: 20px;
		border-left: 4px solid #1976d2;
		font-size: 0.95em;
	}

	.controls {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
		gap: 15px;
		margin-bottom: 20px;
		align-items: end;
	}

	.controls label {
		display: flex;
		flex-direction: column;
		gap: 5px;
		font-weight: 500;
		font-size: 0.9em;
	}

	.controls input,
	.controls select {
		padding: 8px;
		border: 1px solid #ddd;
		border-radius: 4px;
		font-size: 1em;
	}

	.btn-export {
		padding: 8px 16px;
		background-color: #1976d2;
		color: white;
		border: none;
		border-radius: 4px;
		cursor: pointer;
		font-weight: 500;
		transition: background-color 0.2s;
	}

	.btn-export:hover:not(:disabled) {
		background-color: #1565c0;
	}

	.btn-export:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.summary {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
		gap: 15px;
		margin-bottom: 20px;
	}

	.summary-card {
		color: white;
		padding: 15px;
		border-radius: 8px;
		text-align: center;
	}

	.summary-card.total-card {
		background-color: #333;
	}

	.person-name {
		font-size: 0.9em;
		opacity: 0.9;
	}

	.person-total {
		font-size: 1.8em;
		font-weight: bold;
		margin-top: 5px;
	}

	.person-percent {
		font-size: 0.85em;
		opacity: 0.8;
		margin-top: 5px;
	}

	.loading,
	.no-data {
		text-align: center;
		padding: 20px;
		color: #999;
	}

	.meals-table {
		width: 100%;
		border-collapse: collapse;
		background: white;
		border: 1px solid #ddd;
		border-radius: 4px;
		overflow-x: auto;
	}

	.meals-table thead {
		background-color: #f5f5f5;
		position: sticky;
		top: 0;
	}

	.meals-table th,
	.meals-table td {
		padding: 10px;
		text-align: center;
		border-bottom: 1px solid #eee;
	}

	.meals-table th {
		font-weight: bold;
		min-width: 80px;
	}

	.date-cell {
		text-align: left;
		font-weight: 600;
		min-width: 120px;
	}

	.total-cell {
		font-weight: 600;
		background-color: #f0f0f0;
	}

	/* Alternance de couleurs (rose/blanc comme ALO) */
	.meals-table tbody tr:nth-child(odd) {
		background-color: #fce4ec;
	}

	.meals-table tbody tr:nth-child(even) {
		background-color: white;
	}

	.totals-row {
		background-color: #f0f0f0 !important;
		font-weight: bold;
		border-top: 2px solid #ddd;
		border-bottom: 2px solid #ddd;
	}

	.meal-input {
		width: 50px;
		padding: 6px 4px;
		text-align: center;
		border: 1px solid #ccc;
		border-radius: 3px;
		font-size: 0.9em;
		background-color: white;
		transition: border-color 0.2s;
	}

	.meal-input:focus {
		outline: none;
		border-color: #1976d2;
		box-shadow: 0 0 4px rgba(25, 118, 210, 0.2);
	}
</style>
